import {
  // Original icons
  Utensils,
  ShoppingCart,
  ShoppingBag,
  Car,
  HeartPulse,
  Tv,
  GraduationCap,
  Home,
  Plane,
  Sparkles,
  Repeat,
  Fuel,
  Zap,
  Users,
  Gift,
  TrendingUp,
  Landmark,
  Tag,
  Banknote,
  Briefcase,
  ArrowLeftRight,
  // Food & Drink
  Pizza,
  Coffee,
  Cake,
  Beer,
  Wine,
  Cookie,
  Sandwich,
  IceCream,
  Fish,
  Soup,
  Salad,
  // Transport
  Bus,
  Train,
  Bike,
  Ship,
  Truck,
  Gauge,
  // Shopping
  Store,
  Package,
  Shirt,
  Gem,
  Watch,
  Glasses,
  // Health & Fitness
  Heart,
  Pill,
  Activity,
  Thermometer,
  Stethoscope,
  Dumbbell,
  Baby,
  // Entertainment
  Music,
  Headphones,
  Camera,
  Film,
  Gamepad2,
  BookOpen,
  Ticket,
  Trophy,
  PartyPopper,
  // Home
  Sofa,
  Bed,
  Lamp,
  Wrench,
  Wifi,
  Hammer,
  Droplets,
  // Finance
  Wallet,
  CreditCard,
  PiggyBank,
  DollarSign,
  Receipt,
  Coins,
  Percent,
  // Work
  Laptop,
  Phone,
  Monitor,
  Server,
  Code2,
  Mail,
  Printer,
  Pen,
  // Personal
  Scissors,
  Star,
  Bell,
  Shield,
  Lock,
  Key,
  Calendar,
  Clock,
  User,
  // Other
  Globe,
  Map,
  Compass,
  Leaf,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  type LucideProps,
} from "lucide-react";
import { type ComponentType } from "react";

const iconMap: Record<string, ComponentType<LucideProps>> = {
  // Original
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  car: Car,
  "heart-pulse": HeartPulse,
  tv: Tv,
  "graduation-cap": GraduationCap,
  home: Home,
  plane: Plane,
  sparkles: Sparkles,
  repeat: Repeat,
  fuel: Fuel,
  zap: Zap,
  users: Users,
  gift: Gift,
  "trending-up": TrendingUp,
  landmark: Landmark,
  tag: Tag,
  banknote: Banknote,
  briefcase: Briefcase,
  "arrow-left-right": ArrowLeftRight,
  // Food & Drink
  pizza: Pizza,
  coffee: Coffee,
  cake: Cake,
  beer: Beer,
  wine: Wine,
  cookie: Cookie,
  sandwich: Sandwich,
  "ice-cream": IceCream,
  fish: Fish,
  soup: Soup,
  salad: Salad,
  // Transport
  bus: Bus,
  train: Train,
  bike: Bike,
  ship: Ship,
  truck: Truck,
  motorcycle: Gauge,
  // Shopping
  store: Store,
  package: Package,
  shirt: Shirt,
  gem: Gem,
  watch: Watch,
  glasses: Glasses,
  // Health & Fitness
  heart: Heart,
  pill: Pill,
  activity: Activity,
  thermometer: Thermometer,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  baby: Baby,
  // Entertainment
  music: Music,
  headphones: Headphones,
  camera: Camera,
  film: Film,
  "gamepad-2": Gamepad2,
  "book-open": BookOpen,
  ticket: Ticket,
  trophy: Trophy,
  "party-popper": PartyPopper,
  // Home
  sofa: Sofa,
  bed: Bed,
  lamp: Lamp,
  wrench: Wrench,
  wifi: Wifi,
  hammer: Hammer,
  droplets: Droplets,
  // Finance
  wallet: Wallet,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  "dollar-sign": DollarSign,
  receipt: Receipt,
  coins: Coins,
  percent: Percent,
  // Work
  laptop: Laptop,
  phone: Phone,
  monitor: Monitor,
  server: Server,
  "code-2": Code2,
  mail: Mail,
  printer: Printer,
  pen: Pen,
  // Personal
  scissors: Scissors,
  star: Star,
  bell: Bell,
  shield: Shield,
  lock: Lock,
  key: Key,
  calendar: Calendar,
  clock: Clock,
  user: User,
  // Other
  globe: Globe,
  map: Map,
  compass: Compass,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  umbrella: Umbrella,
};

export function CategoryIcon({
  icon,
  className,
  color,
}: {
  icon: string;
  className?: string;
  color?: string;
}) {
  const Icon = iconMap[icon] ?? Tag;
  return <Icon className={className} color={color} />;
}
